image: elixir:1.9-alpine

variables:
  MIX_ENV: test
test:
  stage: test
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only test
  script:
    - mix test
  only:
    - merge_requests
    - master
